apiVersion: v1
kind: Secret
metadata:
  name: emart-sql-secrets
type: Opaque
data:
  sql-password: "ZW1hcnRkYnBhc3M="
  database-name: "ZW1hcnQ="
---
apiVersion: v1
kind: Secret
metadata:
  name: emart-mongo-secrets
type: Opaque
data:
  mongo-root-user: "YWRtaW4="
  mongo-root-password: "YWRtaW4="
  mongo-root-db: "ZXBvYw=="
