apiVersion: apps/v1
kind: Deployment
metadata:
  name: emart-book-deployment
  labels:
    app: emart-book-repo #0001 - Match this two togheter to explicitly tight them
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emart-book-repo #0001 - Match this two togheter to explicitly tight them
  template:
    metadata:
      labels:
        app: emart-book-repo #0001 - Match this two togheter to explicitly tight them
    spec:
      containers:
      - name: emart-book-repo
        image: 084828572941.dkr.ecr.us-east-1.amazonaws.com/emart-book-repository:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
      imagePullSecrets:
      - name: aws-ecr-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: emart-book-service
spec:
  selector:
    app: emart-book-repo   #0001 - Match this two togheter to explicitly tight them
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP